### ISSUE TITLE
Window disappearing

### ISSUE THREAD

**Issue by namp** [mlx-chat/mlx-chat-app#31]
If there's a click anywhere except on the pop up window it disappears without any way of bringing it back unless the app is restarted (npm run dev)

**Comment by namp** [comment]
Solved by commenting out 

win.hide();

at line 279 in main.ts

**Comment by ParkerSm1th** [comment]
Hey @namp! Thanks for using mlx chat.

This is actually intentional as we want it to be similar to spotlight. If you click Cmd + , you can open the settings menu to set your keybind. By default it is Cmd + O to toggle the popup.

**Comment by namp** [comment]
Ahh I see. 

Thank you very much for your reply!
